language: objective-c

os: osx

install:
  - brew install wget
  - wget http://downloads.sourceforge.net/project/macpkg/XZ/5.0.5/XZ.pkg?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmacpkg%2Ffiles%2FPyGTK%2F2.24.0%2F&ts=1473913301&use_mirror=superb-sea2
  - installer -pkg PyGTK.pkg -target /
  - pip install py2app

script:
  - python test/test_base.py
  - python setup.py py2app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Akih+lPnXwxWXEtjlQIDBKaOCuqnk6yP2xKhc/3oLHkD/wWHDCwo10LVZYz7p0aIES922NvsitHPICDdAW1xnUogYfukCMkiqsYQXoM5RNcT+xeufwph9XiVYLhfzZn8HrQW/GyhaI34m9WLqbjSVb/iWxsDZ/NuAMtdMMenJXN/4xQHrJXCLtrdz+HR59PPS9/S5UbfGbx0N27tY5XoaoqDj+SyBFOsveM2Z3EEfKZaozfk+FRc0nBXZInVQr11/MLCgIXE2L9IoPUQNd6RJPQqaP1PkK4f4D+CDoBe1rfsphr2/Er6yLF3JwSZuh8GGKyyBEonHVJBpO/tKf8boWBVGgKEcgNA1PYAody682hfg8zfnuYvaeQNX1RPf28Phay7ITv1aE8RGjaj/Mr45iNPjGh1OJXM9GH/Ucpbs70GDZBlIO2PBwfiD/K2cc8Z1oeTeEf7VgpWqNu/+EAV0XtBLy3ERS/+qU5sj6XTxphSVfF3L0CMgMw9UpmGll+TzYTAcOaXULL4zNo/A4EyZ71C4qJ8dNMnZhs2cRcRgUBGfjlsP14nn/vKup6EuzKZMmtXCo48U/1Fp5uUa2YZBKEnFzd24/TzLTt7sVOgWtjAoSkQY5zHudXpp0gkih/0SeVuQCp7IH1fp88Vyc1xo13G1kpfP9B/7jIUNhYvzlA=
  file: dist/main.app
  on:
    repo: Myoldmopar/EPLaunchLight
    tags: true
