language: python
python:
- 2.7
install: true
script:
- python test/test_base.py

# take out this dummy deployment until we figure out how to actually build proper packages
#- python build_product.py
#deploy:
#  provider: releases
#  api_key:
#    secure: NRtqOfdZggGTOvizm95z9PbFId1g0U8ziZlogvKJPWgqr70vbKTXyXN7j3nQklyYSDbaanz06/rYuBQM6MGl/9X3otbCU1wemL/llCLLGw6lN3JQwsnTvJDbVz4d8DRCfDNZ/gpiGbaxbLm+Xy/ICdagQu0mZQ/V2p6HvHfEicwo7HP4XEHE0wjhNKXjT4QrXUYb+kENmhd8ItMnR653CMMN5jfssN3wgOL5ZA/bq+Y2gCLs9HRL3BEWUACS9tOVvpKdVNpW4OnkP7LIVgRZ84nAGc/TSoRc3hXVJDEDKYjD91xHAZ8Wq05gumIXbX5WyQzne1MQ5D74CKB5A21TPY0OaPkE5bupGluHYSGbPijYJ6DNCDLmMVJc2ncxnXC+CFmhG+Lm2zHRlnJwvEoGvUy3BaGuCBShzQGuqYTH0V3zt+UoPznjAqBssoqEofWdk174eEBYXdjzQoeYrS8BkIV4abRO+8qfBFY21nbl+yb0bLjmP4ioL0bjb1MFt7uxakKsmTYkgiIUMCbICMeLgXiRZb6hS/89fCV/HiwUDlM4FdzyiNtwaHFGHFfcgkKb9bEf1lrTvs0J//vg77uVPAKiHjOA3GzI5AhNGfKBAOXh20r8qrU83fWWJc8hUVl5K0On5HS3OLSIKeFHH93Wfk6n9CPms0hbjXUwTYAjEgw=
#  skip_cleanup: true
#  file: built_product.txt
#  on:
#    repo: Myoldmopar/EPLaunchLight
