"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


setup(
    app=['EP-Launch-Lite.py'],
    data_files=[],
    options={'py2app': {'argv_emulation': True}},
    setup_requires=['py2app'],
)
