name: Mac Releases

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mac_release:
    runs-on: macos-10.15
    permissions:
      # Needed permission to upload the release asset
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install GObject stuff
      run: brew install pygobject3 gtk+3 tree

#    - name: Install Python Packages
#      run: pip install pycairo

    - name: Package up the bundle
      run: python3 setup.py py2app

    - name: Inspect bundle
      run: tree .

    - name: Upload asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/EnergyPlus-*-x86_64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true