name: Build Package and Run Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install System dependencies and LaTeX
        shell: bash
        run: sudo apt-get install -y python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev
      - name: Install Pip Dependencies
        run: pip install ${{ matrix.pip_arg }} -r requirements.txt
      - name: Run Tests
        run: nosetests --with-coverage --cover-package EPLaunchLite  # --cover-html for local html results
